import type { ActionId, Estimate, Evaluation, RiskResult } from '../api/contracts.generated';
const usd = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 });
const number = new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 });
export function EstimateView({ estimate, label }: { estimate: Estimate | null; label: string }) {
  if (!estimate) return <div className="metric"><span>{label}</span><strong>Unknown</strong><small>Evidence is not available for this scenario.</small></div>;
  const format = estimate.unit === 'usd' ? usd.format : number.format;
  return <div className="metric"><span>{label}</span><strong>{format(estimate.point)} <small>point · {estimate.unit.replaceAll('_', ' ')}</small></strong><small>{format(estimate.low)}–{format(estimate.high)} · Scenario range</small><p>{estimate.basis}</p></div>;
}
export function RiskMetrics({ risk }: { risk: RiskResult }) {
  return <><EstimateView label="Rerun GPU-hours" estimate={risk.rerun_gpu_hours}/><EstimateView label="Rerun reference cost" estimate={risk.rerun_reference_cost_usd}/><EstimateView label="Additional CPU core-hours" estimate={risk.additional_cpu_core_hours}/><EstimateView label="Additional CPU cost" estimate={risk.additional_cpu_cost_usd}/><EstimateView label="Added job hours" estimate={risk.added_job_hours}/><div className="unknown"><strong>Cash savings</strong><span>Unknown — no billing evidence</span></div>{risk.unknowns.length > 0 && <ul>{risk.unknowns.map(item => <li key={item}>{item}</li>)}</ul>}</>;
}
export function DecisionCards({ evaluation, inspected, onInspect, onEvidence }: { evaluation: Evaluation; inspected: ActionId; onInspect: (id: ActionId) => void; onEvidence: (id: ActionId) => void }) {
  const action = evaluation.actions.find(item => item.action_id === inspected) ?? evaluation.actions[0];
  const selected = evaluation.portfolio.selected_action_ids.includes(action.action_id);
  const risk = selected ? action.marginal_risk : action.standalone_risk;
  return <section className="decision-cards" aria-label="Decision summary">
    <article className="card" data-evaluation-id={evaluation.meta.evaluation_id}><p className="card-index">01 · HISTORICAL SAMPLE</p><h2>Where the money goes</h2><div className="hero-number">{usd.format(evaluation.baseline.reference_cost_usd)}</div><p>Reference USD across {number.format(evaluation.baseline.measured_gpu_hours)} measured GPU-hours.</p><p>{evaluation.baseline.jobs} jobs · {evaluation.baseline.gpu_rows} physical GPU records</p><div className="table-wrap"><table aria-label="All job outcomes"><thead><tr><th>Outcome</th><th>Jobs</th><th>Measured GPU-h</th><th>Reference USD</th><th>Share</th></tr></thead><tbody>{evaluation.baseline.outcomes.map(row => <tr key={row.state_name}><td>{row.state_name}</td><td>{row.jobs}</td><td>{number.format(row.measured_gpu_hours)}</td><td>{usd.format(row.reference_cost_usd)}</td><td>{number.format(row.share_of_measured_gpu_hours * 100)}%</td></tr>)}</tbody></table></div><details><summary>Method and caveats</summary><p>Computed utilization is a proxy, not verified waste. {number.format(evaluation.baseline.computed_proxy_gpu_hours)} computed proxy GPU-hours; {number.format(evaluation.baseline.completed_computed_proxy_gpu_hours)} completed proxy GPU-hours. Non-completed share of compute proxy: {number.format(evaluation.baseline.non_completed_compute_share * 100)}%.</p><p>Measured GPU-hours use physical GPU duration. Candidate hours may be capped to job walltime. Idle threshold is 4 hours; there is no measured idle-tail duration. Risk inputs are scenario assumptions.</p>{evaluation.baseline.caveats.map(c => <p key={c}>{c}</p>)}</details></article>
    <article className="card" data-evaluation-id={evaluation.meta.evaluation_id}><p className="card-index">02 · RECOMMENDED ACTION</p><h2>Where to cut</h2><div className="action-switch">{evaluation.actions.map(item => <button aria-pressed={item.action_id === action.action_id} key={item.action_id} onClick={() => onInspect(item.action_id)}>{item.title}</button>)}</div><p className="owner">Rank {action.rank} · Owner {action.owner_role} · Effort {action.effort}</p><p>{action.action}</p><p>Ranking basis: {evaluation.ranking_basis}</p>{action.action_id === 'idle_session_reclaim' && <p>Pilot: reminder at 3.5 hours, followed by a 0.5-hour grace period.</p>}<EstimateView label="Standalone recoverable capacity" estimate={action.standalone_recoverable_gpu_hours}/><EstimateView label="Standalone reference savings" estimate={action.standalone_reference_savings_usd}/>{selected ? <><EstimateView label="Marginal recoverable capacity" estimate={action.marginal_recoverable_gpu_hours}/><EstimateView label="Marginal reference savings" estimate={action.marginal_reference_savings_usd}/></> : <p>Not selected in the applied portfolio; standalone scope.</p>}<p>{action.candidate_jobs} candidate jobs · {action.excluded_jobs} excluded jobs · {action.finding_count} findings · {evaluation.portfolio.overlap_jobs} overlap jobs</p>{action.warnings.map(item => <p key={item}>{item}</p>)}{action.exclusion_counts.map(item => <p key={item.reason}>{item.reason}: {item.jobs} jobs</p>)}<button className="primary" data-testid={`evidence-${action.action_id}`} onClick={() => onEvidence(action.action_id)}>View evidence</button></article>
    <article className="card" data-evaluation-id={evaluation.meta.evaluation_id}><p className="card-index">03 · DOWNSIDE</p><h2>If this decision is wrong</h2><p className="scope-pill">{selected ? 'Marginal scope' : 'Standalone scope'} · {action.title}</p>{risk ? <RiskMetrics risk={risk}/> : <p>Unknown risk for this scope</p>}<details><summary>Pilot guardrails</summary><h3>Success metrics</h3><ul>{action.pilot.success_metrics.map(item => <li key={item}>{item}</li>)}</ul><h3>Stop conditions</h3><ul>{action.pilot.stop_conditions.map(item => <li key={item}>{item}</li>)}</ul><h3>Rollback</h3><ul>{action.pilot.rollback_steps.map(item => <li key={item}>{item}</li>)}</ul></details></article>
  </section>;
}
