import type { Bounds, Evaluation, EvaluationRequest } from '../api/contracts.generated';
import { sameValue } from '../api/client';
const numeric = (value: string) => value === '' ? Number.NaN : Number(value);
const valid = (value: number, max = 1000000) => Number.isFinite(value) && value >= 0 && value <= max;
export function validScenario(request: EvaluationRequest) {
  return valid(request.pricing.usd_per_gpu_hour) && (request.pricing.usd_per_cpu_core_hour == null || valid(request.pricing.usd_per_cpu_core_hour)) &&
    [request.cpu_migration, request.idle_session_reclaim].every(action => Object.entries(action).every(([key, bounds]) => bounds === null ||
      [bounds.low, bounds.point, bounds.high].every(value => valid(value, key.includes('fraction') || key.includes('rerun') ? 1 : 1000000)) && bounds.low <= bounds.point && bounds.point <= bounds.high));
}
function BoundsInput({ label, value, optional, onChange }: { label: string; value: Bounds | null; optional: boolean; onChange: (bounds: Bounds | null) => void }) {
  return <fieldset><legend>{label}</legend>{optional && <label><input type="checkbox" aria-label={`${label} Unknown`} checked={value === null} onChange={event => onChange(event.target.checked ? null : { low: NaN, point: NaN, high: NaN })}/>Unknown</label>}{value && <div className="bounds">{(['low', 'point', 'high'] as const).map(key => <label key={key}>{key}<input type="number" step="any" min="0" aria-label={`${label} ${key}`} value={Number.isFinite(value[key]) ? value[key] : ''} onChange={event => onChange({ ...value, [key]: numeric(event.target.value) })}/></label>)}</div>}</fieldset>;
}
export function ScenarioForm({ draft, evaluation, updating, onChange, onApply }: { draft: EvaluationRequest; evaluation: Evaluation; updating: boolean; onChange: (request: EvaluationRequest) => void; onApply: () => void }) {
  return <section className="scenario-form" aria-label="Scenario inputs"><div className="scenario"><label>GPU reference price<input type="number" step="any" min="0" max="1000000" value={Number.isFinite(draft.pricing.usd_per_gpu_hour) ? draft.pricing.usd_per_gpu_hour : ''} onChange={event => onChange({ ...draft, pricing: { ...draft.pricing, usd_per_gpu_hour: numeric(event.target.value) } })}/></label><label>CPU reference price (blank is Unknown)<input type="number" step="any" min="0" max="1000000" value={draft.pricing.usd_per_cpu_core_hour ?? ''} onChange={event => onChange({ ...draft, pricing: { ...draft.pricing, usd_per_cpu_core_hour: event.target.value === '' ? null : Number(event.target.value) } })}/></label><div className="checks">{evaluation.actions.map(action => <label key={action.action_id}><input type="checkbox" checked={draft.selected_action_ids.includes(action.action_id)} onChange={event => onChange({ ...draft, selected_action_ids: event.target.checked ? [...draft.selected_action_ids, action.action_id] : draft.selected_action_ids.filter(id => id !== action.action_id) })}/>{action.title}</label>)}</div><button className="primary" disabled={!validScenario(draft) || updating} onClick={onApply}>Apply scenario</button></div>{!sameValue(draft, evaluation.request) && <p role="status">Unapplied changes</p>}<details><summary>Advanced scenario assumptions</summary><p>Ranges are scenario assumptions, not confidence intervals. Enter low ≤ point ≤ high; fractions must be at most 1. Unknown inputs remain unknown.</p>{(['cpu_migration', 'idle_session_reclaim'] as const).map(action => <div key={action}>{Object.entries(draft[action]).map(([key, value]) => {
    const labels: Record<string, string> = { recoverable_fraction: 'recoverable fraction', rerun_gpu_hours_per_candidate_gpu_hour: 'rerun fraction', additional_cpu_core_hours_per_gpu_hour: 'CPU core-hours per GPU-hour', added_elapsed_hours_per_job: 'added elapsed hours per job' };
    return <BoundsInput key={key} label={`${action === 'cpu_migration' ? 'CPU' : 'Idle'} ${labels[key]}`} value={value} optional={key !== 'recoverable_fraction'} onChange={bounds => onChange({ ...draft, [action]: { ...draft[action], [key]: bounds } })}/>;
  })}</div>)}</details>{!validScenario(draft) && <p role="alert">Complete each known range with finite, nonnegative, ordered values before applying.</p>}</section>;
}
